### ISSUE TITLE
Products catalog is indexed, has data, but has no results

### ISSUE THREAD

**Issue by mglaman** [drupalcommerce/demo-project#11]
## Current

Search API bug report: https://www.drupal.org/project/search_api/issues/2949379

Fix/workaround is in commerce_demo

## Original
The catalog has no data being rendered by Views even though the index has data.

![demo-project____drupal_commerce_demo-project__-_search_api_db_products___sqlite_](https://user-images.githubusercontent.com/3698644/36874911-634b31be-1d73-11e8-94d7-07ae1fb84df7.png)

**Comment by mglaman** [comment]
When the View is executed

```
    0 => "No available query types were found for facet Brand"
```

And the Search API query is aborted.

**Comment by mglaman** [comment]
Looks like there is a weird issue on fields being available. They're missing from the index once imported.

**Comment by mglaman** [comment]
@bojanz I wonder if we need more hardcore config dependencies. Or move them to optional.

**Comment by bojanz** [comment]
Opened a bug report: https://www.drupal.org/project/search_api/issues/2949379
Moved the workaround to commerce_demo: https://github.com/bojanz/commerce_demo/commit/f21c353b3c117aa9524896190db7de29b937158c
Also had to trigger a reindex, unsure why.

**Comment by mglaman** [comment]
Okay, I can remove the hack in here later. I wasn't sure if it'd be enough inside of the demo module.

**Comment by mglaman** [comment]
Removed milestone, it's blocked by an upstream contrib.

**Comment by mglaman** [comment]
Interesting, Facets has an issue too

When trying to revert those and import...

```
  $config_updater->revert([
    'search_api.server.database',
    'search_api.index.products',
    'facets.facet_source.search_api__views_page__product_catalog__page_1',
    'facets.facet.brand',
    'facets.facet.product_categories',
    'facets.facet.special_categories',
  ], FALSE);
```

This happens!

```
Error: Call to a member function uuid() on null in /Users/mglaman/Drupal/commerce/demo-project/web/modules/contrib/commerce/src/Config/ConfigUpdater.php on line 158 #0 /Users/mglaman/Drupal/commerce/demo-project/web/modules/contrib/commerce_demo/commerce_demo.install(26): Drupal\commerce\Config\ConfigUpdater->revert(Array, false)
#1 [internal function]: commerce_demo_install()
#2 /Users/mglaman/Drupal/commerce/demo-project/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(391): call_user_func_array('commerce_demo_i...', Array)
#3 /Users/mglaman/Drupal/commerce/demo-project/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(298): Drupal\Core\Extension\ModuleHandler->invoke('commerce_demo', 'install')
#4 /Users/mglaman/Drupal/commerce/demo-project/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\Core\Extension\ModuleInstaller->install(Array, false)
#5 /Users/mglaman/Drupal/commerce/demo-project/web/core/includes/install.core.inc(1805): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, false)
#6 /Users/mglaman/Drupal/commerce/demo-project/web/core/includes/batch.inc(294): _install_module_batch('commerce_demo', 'Commerce Demo', Array)
#7 /Users/mglaman/Drupal/commerce/demo-project/web/core/includes/form.inc(875): _batch_process()
#8 /Users/mglaman/Drupal/commerce/demo-project/web/core/includes/install.core.inc(628): batch_process(Object(Drupal\Core\Url), Object(Drupal\Core\Url))
#9 /Users/mglaman/Drupal/commerce/demo-project/web/core/includes/install.core.inc(549): install_run_task(Array, Array)
#10 /Users/mglaman/Drupal/commerce/demo-project/web/core/includes/install.core.inc(117): install_run_tasks(Array)
#11 /Users/mglaman/Drupal/commerce/demo-project/scripts/demo/DemoInstallCommand.php(160): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#12 /Users/mglaman/Drupal/commerce/demo-project/scripts/demo/DemoInstallCommand.php(66): DemoCommerce\DemoInstallCommand->install(Object(Composer\Autoload\ClassLoader), Object(Symfony\Component\Console\Output\ConsoleOutput), 'demo_commerce', 'en')
#13 /Users/mglaman/Drupal/commerce/demo-project/vendor/symfony/console/Command/Command.php(252): DemoCommerce\DemoInstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /Users/mglaman/Drupal/commerce/demo-project/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /Users/mglaman/Drupal/commerce/demo-project/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(DemoCommerce\DemoInstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /Users/mglaman/Drupal/commerce/demo-project/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /Users/mglaman/Drupal/commerce/demo-project/scripts/demo-install.php(21): Symfony\Component\Console\Application->run()
#18 {main}
Error: Call to a member function uuid() on null in Drupal\commerce\Config\ConfigUpdater->revert() (line 158 of /Users/mglaman/Drupal/commerce/demo-project/web/modules/contrib/commerce/src/Config/ConfigUpdater.php).
Starting webserver on http://localhost:52052
```

**Comment by mglaman** [comment]
This fixed it.

```
  $config_updater->revert([
    'search_api.server.database',
    'search_api.index.products',
  ], FALSE);
  $config_updater->import([
    'facets.facet_source.search_api__views_page__product_catalog__page_1',
    'facets.facet.brand',
    'facets.facet.product_categories',
    'facets.facet.special_categories',
  ]);
```
