### ISSUE TITLE
Cannot do a site:install using Drupal Console

### ISSUE THREAD

**Issue by ProCycle** [drupalcommerce/demo-project#36]
When I try to install the site using Drupal Console with the demo_commerce profile I get an error which prevents the install from continuing. If I use the standard profile instead then it installs without issue

Steps:

```
composer create-project drupalcommerce/demo-project demo-commerce --stability dev --no-interaction
cd demo-commerce
drupal site:install commerce_base --db-type="mysql" --db-host="127.0.0.1" --db-port="3306" --db-name="commercedemo" --db-user="demo" --site-name="Commerce Demo" --site-mail="info@example.com" --account-name="administrator" --account-mail="administrator@example.com"
```

Results in the error:

```
 Starting Drupal 8 install process
Error: Class 'Drupal\bootstrap\Bootstrap' not found in /srv/www/commercedemo.procycle.local/web/themes/contrib/bootstrap/bootstrap.theme on line 31 #0 /srv/www/commercedemo.procycle.local/web/core/lib/Drupal/Core/Extension/Extension.php(140): include_once()
#1 /srv/www/commercedemo.procycle.local/web/core/themes/engines/twig/twig.engine(35): Drupal\Core\Extension\Extension->load()
#2 [internal function]: twig_init(Object(Drupal\Core\Extension\Extension))
#3 /srv/www/commercedemo.procycle.local/web/core/lib/Drupal/Core/Theme/ThemeInitialization.php(144): call_user_func('twig_init', Object(Drupal\Core\Extension\Extension))
#4 /srv/www/commercedemo.procycle.local/web/core/lib/Drupal/Core/Theme/ThemeManager.php(122): Drupal\Core\Theme\ThemeInitialization->loadActiveTheme(Object(Drupal\Core\Theme\ActiveTheme))
#5 /srv/www/commercedemo.procycle.local/web/core/includes/theme.maintenance.inc(99): Drupal\Core\Theme\ThemeManager->setActiveTheme(Object(Drupal\Core\Theme\ActiveTheme))
#6 /srv/www/commercedemo.procycle.local/web/core/includes/bootstrap.inc(740): _drupal_maintenance_theme()
#7 /srv/www/commercedemo.procycle.local/web/core/includes/install.core.inc(493): drupal_maintenance_theme()
#8 /srv/www/commercedemo.procycle.local/web/core/includes/install.core.inc(114): install_begin_request(Object(Composer\Autoload\ClassLoader), Array)
#9 /srv/www/commercedemo.procycle.local/vendor/drupal/console/src/Command/Site/InstallCommand.php(542): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#10 /srv/www/commercedemo.procycle.local/vendor/drupal/console/src/Command/Site/InstallCommand.php(433): Drupal\Console\Command\Site\InstallCommand->runInstaller(Array, 'default')
#11 /srv/www/commercedemo.procycle.local/vendor/symfony/console/Command/Command.php(251): Drupal\Console\Command\Site\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /srv/www/commercedemo.procycle.local/vendor/symfony/console/Application.php(964): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /srv/www/commercedemo.procycle.local/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Drupal\Console\Command\Site\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /srv/www/commercedemo.procycle.local/vendor/drupal/console-core/src/Application.php(185): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /srv/www/commercedemo.procycle.local/vendor/drupal/console/src/Application.php(64): Drupal\Console\Core\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /srv/www/commercedemo.procycle.local/vendor/symfony/console/Application.php(148): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /srv/www/commercedemo.procycle.local/vendor/drupal/console/bin/drupal.php(89): Symfony\Component\Console\Application->run()
#18 /srv/www/commercedemo.procycle.local/vendor/drupal/console/bin/drupal(4): require('/srv/www/commer...')
#19 {main}
Error: Class &#039;Drupal\bootstrap\Bootstrap&#039; not found in include_once() (line 31 of /srv/www/commercedemo.procycle.local/web/themes/contrib/bootstrap/bootstrap.theme).
```

**Comment by mglaman** [comment]
Relevant issue: https://www.drupal.org/project/bootstrap/issues/2667062

**Comment by dwkitchen** [comment]
Can no longer reproduce
