### ISSUE TITLE
composer create-project drupalcommerce/demo-project demo-commerce --stability dev --no-interaction when use composer to create the project

### ISSUE THREAD

**Issue by lawxen** [drupalcommerce/demo-project#60]
```
Fatal error: Uncaught Error: Undefined constant "DrupalProject\composer\CONFIG_SYNC_DIRECTORY" in /var/www/demo-commerce/scripts/composer/ScriptHandler.php:44
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(388): DrupalProject\composer\ScriptHandler::createRequiredFiles(Object(Composer\Script\Event))
#1 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(237): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('DrupalProject\\c...', 'createRequiredF...', Object(Composer\Script\Event))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(118): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/Installer.php(364): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-update-cmd', true)
#4 phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php(267): Composer\Installer->run()
#5 phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php(164): Composer\Command\CreateProjectCommand->installProject(Object(Composer\IO\ConsoleIO), Object(Composer\Config), Object(Symfony\Component\Console\Input\ArgvInput), 'drupalcommerce/...', 'demo-commerce', NULL, 'dev', false, true, true, NULL, false, false, false, false, false, true, false)
#6 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\CreateProjectCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\CreateProjectCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(327): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar:///usr/local/bin/composer/bin/composer(73): Composer\Console\Application->run()
#13 /usr/local/bin/composer(29): require('phar:///usr/loc...')
#14 {main}
  thrown in /var/www/demo-commerce/scripts/composer/ScriptHandler.php on line 44

```

**Comment by LubomirKurpel** [comment]
Having the same problem here. Did you find a solution?
